eStore/Models/CategoryViewModel.cs
using BusinessObject;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace eStore.Models;

public class CategoryViewModel
{
    public int CategoryId { get; set; }
    public List<SelectListItem> Categories { get; } = new List<SelectListItem>();

    public CategoryViewModel(IEnumerable<Category> categories)
    {
        foreach (var item in categories)
        {
            Categories.Add(new SelectListItem
            {
                Value = item.CategoryId.ToString(),
                Text = item.CategoryName
            });
        }
    }
}

eStore/Models/ErrorViewModel.cs
namespace eStore.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

eStore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using eStore.Models;

namespace eStore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

eStore/Controllers/MemberController.cs
using System.Net.Http.Headers;
using BusinessObject;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace eStore.Controllers;

public class MemberController : Controller
{
    private readonly HttpClient client = null;
    private string MemberApiUrl = "";

    public MemberController()
    {
        client = new HttpClient();
        var contentType = new MediaTypeWithQualityHeaderValue("application/json");
        client.DefaultRequestHeaders.Accept.Add(contentType);
        MemberApiUrl = "https://localhost:7141/member";
    }

    public async Task<IActionResult> Index()
    {
        HttpResponseMessage memberResponse = await client.GetAsync(MemberApiUrl);
        List<Member>? listMembers = new List<Member>();
        if (memberResponse.StatusCode == System.Net.HttpStatusCode.OK)
        {
            listMembers = await memberResponse.Content.ReadFromJsonAsync<List<Member>>();
        }

        return View(listMembers);
    }

    public async Task<IActionResult> Details(int id)
    {
        HttpResponseMessage memberResponse = await client.GetAsync(MemberApiUrl + $"/{id}");
        Member? member = new Member();
        if (memberResponse.StatusCode == System.Net.HttpStatusCode.OK)
        {
            member = await memberResponse.Content.ReadFromJsonAsync<Member>();
        }
        
		return View(member);
    }

    public async Task<ActionResult> Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Member p)
    {
        HttpResponseMessage response =
            await client.PostAsJsonAsync(MemberApiUrl, p);
        if (ModelState.IsValid)
        {
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
        }

        return Redirect("Create");
    }

    public async Task<ActionResult> Edit(int id)
    {
        HttpResponseMessage memberResponse = await client.GetAsync(MemberApiUrl + $"/{id}");
        Member member = new Member();
        if (memberResponse.StatusCode == System.Net.HttpStatusCode.OK)
        {
            member = memberResponse.Content.ReadFromJsonAsync<Member>().Result;
        }

        return View(member);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Edit(int id, Member p)
    {
        if (ModelState.IsValid)
        {
            await client.PutAsJsonAsync(MemberApiUrl + $"/{p.MemberId}", p);
            return RedirectToAction("Index");
        }

        return View(p);
    }

    public async Task<ActionResult> Delete(int id)
    {
        await client.DeleteAsync(MemberApiUrl + $"/{id}");
        return RedirectToAction("Index");
    }
}

eStore/Controllers/ProductController.cs
using System.Dynamic;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using BusinessObject;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.AspNetCore.Mvc.Rendering;
using eStore.Models;

namespace eStore.Controllers;

public class ProductController : Controller
{
    private readonly HttpClient client = null;
    private string ProductApiUrl = "";
    private string CategoryApiUrl = "";

    public ProductController()
    {
        client = new HttpClient();
        var contentType = new MediaTypeWithQualityHeaderValue("application/json");
        client.DefaultRequestHeaders.Accept.Add(contentType);
        ProductApiUrl = "https://localhost:7141/product";
        CategoryApiUrl = "https://localhost:7141/category";
    }

    public async Task<IActionResult> Index()
    {
        HttpResponseMessage productResponse = await client.GetAsync(ProductApiUrl);
        List<Product>? listProducts = new List<Product>();
        if (productResponse.StatusCode == System.Net.HttpStatusCode.OK)
        {
            listProducts = await productResponse.Content.ReadFromJsonAsync<List<Product>>();
        }

        HttpResponseMessage categoryResponse = await client.GetAsync(CategoryApiUrl);
        List<Category>? listCategories = new List<Category>();
        if (categoryResponse.StatusCode == System.Net.HttpStatusCode.OK)
        {
            listCategories = await categoryResponse.Content.ReadFromJsonAsync<List<Category>>();
        }

        ViewData["CategoryId"] = new SelectList(listCategories, "CategoryId", "CategoryName");

        return View(listProducts);
    }

    public async Task<IActionResult> Details(int id)
    {
        HttpResponseMessage productResponse = await client.GetAsync(ProductApiUrl + $"/{id}");
        Product? product = new Product();
        if (productResponse.StatusCode == System.Net.HttpStatusCode.OK)
        {
            product = await productResponse.Content.ReadFromJsonAsync<Product>();
        }

		HttpResponseMessage categoryResponse = await client.GetAsync(CategoryApiUrl);
		List<Category>? listCategories = new List<Category>();
		if (categoryResponse.StatusCode == System.Net.HttpStatusCode.OK)
		{
			listCategories = await categoryResponse.Content.ReadFromJsonAsync<List<Category>>();
		}
		ViewData["category"] = listCategories;
		return View(product);
    }

    public async Task<ActionResult> Create()
    {
        HttpResponseMessage categoryResponse = await client.GetAsync(CategoryApiUrl);
        List<Category>? listCategories = new List<Category>();
        if (categoryResponse.StatusCode == System.Net.HttpStatusCode.OK)
        {
            listCategories = await categoryResponse.Content.ReadFromJsonAsync<List<Category>>();
        }
        ViewData["category"] = listCategories;
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Product p)
    {
        HttpResponseMessage response =
            await client.PostAsJsonAsync(ProductApiUrl, p);
        if (ModelState.IsValid)
        {
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
        }

        return Redirect("Create");
    }

    public async Task<ActionResult> Edit(int id)
    {
        HttpResponseMessage productResponse = await client.GetAsync(ProductApiUrl + $"/{id}");
        Product product = new Product();
        if (productResponse.StatusCode == System.Net.HttpStatusCode.OK)
        {
            product = productResponse.Content.ReadFromJsonAsync<Product>().Result;
        }

        HttpResponseMessage categoryResponse = await client.GetAsync(CategoryApiUrl);
        List<Category>? listCategories = new List<Category>();
        if (categoryResponse.StatusCode == System.Net.HttpStatusCode.OK)
        {
            listCategories = categoryResponse.Content.ReadFromJsonAsync<List<Category>>().Result;
        }
        ViewData["category"] = listCategories;

        return View(product);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Edit(int id, Product p)
    {
        if (ModelState.IsValid)
        {
            await client.PutAsJsonAsync(ProductApiUrl + $"/{p.ProductId}", p);
            return RedirectToAction("Index");
        }

        return View(p);
    }

    public async Task<ActionResult> Delete(int id)
    {
        await client.DeleteAsync(ProductApiUrl + $"/{id}");
        return RedirectToAction("Index");
    }
}

eStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

eStore/Views/Member/Create.cshtml
@model BusinessObject.Member

@{
    var categories = (List<BusinessObject.Category>)ViewData["category"];
}

<form asp-controller="Member" asp-action="Create" method="POST">
    <br/>
    <div class="container border p-3">
        <h1 class="text-white text-center">Create Member</h1>

        <hr/>
        <div class="row">
            <input type="hidden" asp-for="MemberId" value="0" />
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Email</label>
            </div>
            <div class="col-10 pb-3">
                <input type="email" asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Company Name</label>
            </div>
            <div class="col-10 pb-3">
                <input type="text" asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> City</label>
            </div>
            <div class="col-10 pb-3">
                <input type="text" asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Country</label>
            </div>
            <div class="col-10 pb-3">
                <input type="text" asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            
            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control"/>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

eStore/Views/Member/Details.cshtml
@model BusinessObject.Member

<form>
    <br/>
    <div class="container border p-3">
        <h1 class="text-center">Member Details</h1>

        <hr/>
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">ID</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="MemberId" value="@Model.MemberId" class="form-control" disabled/>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Email</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Email" class="form-control" disabled/>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Company Name</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CompanyName" class="form-control" disabled/>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">City</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="City" class="form-control" disabled/>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Country</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Country" class="form-control" disabled/>
            </div>

            <div class="col-10 pb-3">

            </div>
            <div class="col-12">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to List</a>
            </div>
        </div>
    </div>
</form>

eStore/Views/Member/Edit.cshtml
@model BusinessObject.Member


<form asp-controller="Member" asp-action="Edit" method="POST">
    <br/>
    <div class="container border p-3">
        <h1 class="text-white text-center">Edit Member</h1>

        <hr/>
        <div class="row">
            <input asp-for="MemberId" class="form-control" hidden/>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Email</label>
            </div>
            <div class="col-10 pb-3">
                <input type="email" asp-for="Email" class="form-control" disabled/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Company Name</label>
            </div>
            <div class="col-10 pb-3">
                <input type="text" asp-for="CompanyName" class="form-control"/>
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> City</label>
            </div>
            <div class="col-10 pb-3">
                <input type="text" asp-for="City" class="form-control"/>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Country</label>
            </div>
            <div class="col-10 pb-3">
                <input type="text" asp-for="Country" class="form-control"/>
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            
            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Edit" class="btn btn-success form-control"/>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

eStore/Views/Member/Index.cshtml
@model IEnumerable<BusinessObject.Member>

@{
    ViewData["Title"] = "Index";
}

<h1>Members Managements</h1>

<p>
    <a asp-action="Create" class="text-decoration-none">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MemberId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            Actions
        </th>
    </tr>
    </thead>

    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MemberId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.MemberId }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.MemberId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MemberId })
            </td>
        </tr>
    }
    </tbody>
</table>

eStore/Views/Product/Create.cshtml
@model BusinessObject.Product

@{
    var categories = (List<BusinessObject.Category>)ViewData["category"];
}

<form asp-controller="Product" asp-action="Create" method="POST">
    <br/>
    <div class="container border p-3">
        <h1 class="text-white text-center">Create Product</h1>

        <hr/>
        <div class="row">
            <input type="hidden" asp-for="ProductId" value="0" />
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Name</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ProductName" class="form-control"/>
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Unit Price</label>
            </div>
            <div class="col-10 pb-3">
                <input type="number" asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Units In Stock</label>
            </div>
            <div class="col-10 pb-3">
                <input type="number" asp-for="UnitsInStock" class="form-control" />
                <span asp-validation-for="UnitsInStock" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Category</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="CategoryId" class="form-select">
                    @foreach (var item in categories)
                    {
                        <option value="@item.CategoryId">@item.CategoryName</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control"/>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

eStore/Views/Product/Details.cshtml
@model BusinessObject.Product

@{
    var categories = (List<BusinessObject.Category>)ViewData["category"];
}

<form>
    <br/>
    <div class="container border p-3">
        <h1 class="text-center">Product Details</h1>

        <hr/>
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">ID</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ProductId" value="@Model.ProductId" class="form-control" disabled/>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Name</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ProductName" class="form-control" disabled/>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Unit Price</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="UnitPrice" class="form-control" disabled/>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Units In Stock</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="UnitsInStock" class="form-control" disabled/>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Category</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="CategoryId" class="form-select" disabled>
                    @foreach (var item in categories)
                    {
                        <option value="@item.CategoryId">@item.CategoryName</option>
                    }
                </select>
            </div>
            <div class="col-12">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to List</a>
            </div>
        </div>
    </div>
</form>

eStore/Views/Product/Edit.cshtml
@model BusinessObject.Product

@{
    var categories = (List<BusinessObject.Category>)ViewData["category"];
}


<form asp-controller="Product" asp-action="Edit" method="POST">
    <br/>
    <div class="container border p-3">
        <h1 class="text-white text-center">Edit Product</h1>

        <hr/>
        <div class="row">
            <input asp-for="ProductId" class="form-control" hidden/>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Name</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ProductName" class="form-control"/>
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Unit Price</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="UnitPrice" class="form-control"/>
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Units In Stock</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="UnitsInStock" class="form-control"/>
                <span asp-validation-for="UnitsInStock" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Category</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="CategoryId" class="form-select">
                    @foreach (var item in categories)
                    {
                        <option value="@item.CategoryId">@item.CategoryName</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            
            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Edit" class="btn btn-success form-control"/>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

eStore/Views/Product/Index.cshtml
@model IEnumerable<BusinessObject.Product>

@{
	ViewData["Title"] = "Index";
}

<h1>Products Managements</h1>

<p>
	<a asp-action="Create" class="text-decoration-none">Create New</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.ProductId)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ProductName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.UnitPrice)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Category)
			</th>
			<th>
				Actions
			</th>
		</tr>
	</thead>

	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.ProductId)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.ProductName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.UnitPrice)
				</td>
				<td>
					<select class="form-control" asp-items="ViewBag.CategoryId" asp-for="@item.CategoryId" disabled></select>
				</td>
				<td>
					@Html.ActionLink("Details", "Details", new { id = item.ProductId }) |
					@Html.ActionLink("Edit", "Edit", new { id = item.ProductId }) |
					@Html.ActionLink("Delete", "Delete", new { id = item.ProductId })
				</td>
			</tr>
		}
	</tbody>
</table>

eStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - eStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ProductManagementWebClient.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eStore</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Member</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - eStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>